### ISSUE TITLE
Add an unfold method to ReactiveSeq

### ISSUE THREAD

**Issue by johnmcclean-aol** [aol/cyclops-react#102]
Should have the same signature as jOOλ equivalent.

```java
       static <T, U> ReactiveSeq<T> unfold(U seed, Function<U, Optional<Tuple2<T, U>>> unfolder);
```

Implementation can call jOOλ directly and then wrap the resulting Seq as a ReactiveSeq.

**Comment by lukaseder** [comment]
Huh, just noticed, the jOOλ signature is probably incorrect with respect to variance. At least, it should be `Function<? super U, ...>`. Will check about variance within the tuple...

**Comment by johnmcclean-aol** [comment]
Sounds good. I should have some time later today or tomorrow to start taking a look at the shuffle enhancement too.

**Comment by johnmcclean-aol** [comment]
PR : https://github.com/aol/cyclops-react/pull/198
