### ISSUE TITLE
Whether is bug?

### ISSUE THREAD

**Issue by langzhaozhi** [aol/cyclops-react#150]
ReactiveSeq.of( 1,2,3,4,5,6,7,8,9 )
            .map( this::load )
            .forEachEvent( System.out::println, aEx -> System.err.println( aEx + ":" + aEx.getMessage() ), ()-> System.out.println("Over") );

//this::load is simple
String load(int i){
        if( i == 2 ){
            throw new RuntimeException("test exception:" + i);
        }
        else{
            return "xx" + i;
        }
}

when running code above, the printing "Over" happens two times! One for exception, another for real onComplete. Is it a bug ? I think the comletion should happen only once

**Comment by johnmcclean-aol** [comment]
I would have thought so to, let me run and check.

**Comment by johnmcclean-aol** [comment]
This is a bug - spinning a release with a fix for this now.

**Comment by johnmcclean-aol** [comment]
Fixed in 1.0.0-RC2.1 released to Maven Central, should be available for download shortly.

@langzhaozhi  Thanks a million for reporting this!!

**Comment by langzhaozhi** [comment]
It is OK now in RC2.1, reactive-rapid !
