### ISSUE TITLE
AnyM#unwrap() unexpectedly unpacks list to stream

### ISSUE THREAD

**Issue by smillies** [aol/cyclops-react#160]
Hello John,

I've revisited the [state machine code](http://sebastian-millies.blogspot.de/2015/11/deterministic-and-non-deterministic.html) that we talked about a while ago so as to make it work with the changes in cyclops API that have occurred since. The point of that example is to use AnyM to abstract over Optional and List.

I've noticed that the old problem with AnyM#unwrap() has resurfaced, in that it does not unwrap a List to a List, but to a java.util.stream.ReferencePipeline. The code worked with cyclops 6.1.1, I don't know with what later release it started to break.

Perhaps the problem is that I replaced AnyM.ofMonad() - which no longer exists - with AnyM.ofValue(). Anyway, there seems to be no combination of factory method and unwrap method that makes the abstraction work as before. Or is there?

I attach the test case.

Best Regards,
Sebastian
[src.zip](https://github.com/aol/cyclops-react/files/179929/src.zip)

**Comment by johnmcclean-aol** [comment]
Hey Sebastian,

There have been a lot of API changes, with the goal of improving type safety overall. I do plan on documenting these in detail over the next month or so. Hopefully it will make your experience of using cyclops-react more enjoyable and less surprising (particularly around edge case handling)!

The best API call to use for Lists  is 

```java
List<String> l = AnyM.fromList(Arrays.asList(1,2,3))
	                        .map(i->"hello"+i)
	                        .unwrap();
```

The general format for known monad types is to call AnyM.fromXXXX 

You can use AnyM.ofValue or AnyM.ofSeq for (previously) unknown (to cyclops) monad types, but they aren't type safe. The methods exist to help people write extensions. If it is making things more complicated than it needs to be, I'm certainly open to hiding them aways somewhere :) (feedback appreciated!).


AnyM.fromList returns an AnyMSeq (it still wraps a List), as we've created two separate sublasses of AnyM. 

AnyMSeq for Monads that can hold multiple values represented with a single unaggregated type (e.g. List<T> becomes AnyMSeq<T>, but Optional<List<T>> isn't an AnyMSeq).

AnyMValue for Monads that hold a single value. E.g. Optional<T> can become AnyMValue<T> and Optional<List<T>> can become AnyMValue<List<T>>.

This allows us to prevent certain unsafe actions such as returning a Stream / List / Set in a flatMap operation on an Optional (in such scenarios we have to convert to an Optional<List/Set/Stream> which has a conflicting type compared to Optional flatMap Optional or CompletableFuture - which can still be unaggregated).

AnyMSeq can safely recieve an AnyMValue or AnyMSeq as a flatMap result, but the same is not true for AnyMValue. In an early version of cyclops we implemented the Javaslang take first rules as a compromise, but by separating the types I think we can make sure to uphold the monad laws.

Thanks,
John

**Comment by johnmcclean-aol** [comment]
Btw, I'll get back to you with some change to your test case if that is ok.

**Comment by johnmcclean-aol** [comment]
The code below passes both your tests (using ofSeq then treating everything as an AnyMSeq which allows type safe flatMapping).

anyM(Object o) is slightly unsafe. Puting Optional into an AnyMSeq wrapper means it can be flatMapped against a List or Stream. But looking at the code I don't think that can happen so we're probably ok (this edge case was present all a long, the work around was to take the first value from the List).


```java
public abstract class StateMachines {

    @FunctionalInterface
    public interface StateMachine<S, M> {
        M accept(S state, CharSequence input);
    }
    
    /**
     * Create a finite state machine with the given transition function. The transition function may be partial. It is
     * extended to a total function by mapping all undefined values to the given default.
     * <p>
     * If we pass in a transition function that has type <code>Optional&lt;State&gt;</code> we will get a deterministic
     * finite state machine, and if we pass in a function that has type <code>List&lt;State&gt;</code> then we will get
     * a non-deterministc one.
     * 
     * @param partialTransitions possibly partial function taking the current state and the next input character and
     *            returning the next state (or states) wrapped in the monad appropriate to the machine's type
     * @param defaultValue function that supplies the value returned for undefined transitions, representing failure
     * @return a finite state machine based on the given transition function
     */
    public static <S, M> StateMachine<S,M> newStateMachine(BiFunction<S, Character, M> partialTransitions, M defaultValue) {
        Objects.requireNonNull(partialTransitions);
        Objects.requireNonNull(defaultValue);
       
        // Make the given function total, and yield a wrapped monad (from an Optional or List, as the case may be)
        BiFunction<S, Character, AnyMSeq<S>> totalTransitions = (s, c) -> 
            anyM(Optional.ofNullable(partialTransitions.apply(s, c)).orElse(defaultValue));

        // Define how to create a new instance of the underlying monad
        Function<S, AnyMSeq<S>> unit = s -> anyM(defaultValue).unit(s);
        
        // Return a traversal function and unwrap the result to the original type that went into the AnyM construction
        return (state,input) -> machine(totalTransitions, unit).accept(state, input).unwrap();
    }
    
    private static <S> AnyMSeq<S> anyM(Object o){
        return AnyM.ofSeq(o);
    }

    // walk :: Monad m => s -> (s -> Char -> m s) -> [Char] -> m s
    // walk state advance [] = return state
    // walk state advance (i:inputs) = do
    //                                  next <- advance state i
    //                                  walk next advance inputs
    private static <S> StateMachine<S, AnyMSeq<S>> machine(BiFunction<S, Character, AnyMSeq<S>> transitions, Function<S, AnyMSeq<S>> unit) {
        return (state,input) -> {
            if (input.length() == 0) return unit.apply(state);
           
            return transitions.apply(state, input.charAt(0))
                       .flatMap(next -> machine(transitions,unit).accept(next, input.subSequence(1, input.length())));
        };
    }
}
```

**Comment by smillies** [comment]
Thanks for the detailed explanation and corrections! I've linked back to this GitHub issue from a comment on my blog post, so people can see how it works and why.

Given the explanation, I'm ok with AnyM.ofValue and AnyM.ofSeq sitting where they do.

**Comment by johnmcclean-aol** [comment]
Thanks Sebastian!
