### ISSUE TITLE
SimpleReactStream does not capture errors unless block() is called

### ISSUE THREAD

**Issue by johnmcclean-aol** [aol/cyclops-react#174]
Needs a non-blocking terminal operation to collate errors safely inside run().

Releated to https://github.com/aol/cyclops-react/issues/173

**Comment by schoberwirt** [comment]
Ohhhhhh. Interesting! :D

**Comment by johnmcclean-aol** [comment]
Yeah, forcing users to use run() or block() is a bad solution too. Fixing it so that capture is automatically applied only once to SimpleReactStreams.

**Comment by johnmcclean-aol** [comment]
I've added a non-blocking run() method that collate errors for SimpleReact streams.

It's proving pretty complex to do this automatically without such a method, I think we should release the run() fix in 1.0.0-RC2.3 and revist in future releases.

**Comment by johnmcclean-aol** [comment]
Released in 1.0.0-RC2.3

@schoberwirt  Thanks for reporting this issue, do let me know if you still see it (i.e. it's caused by something other than the two issues logged).
