### ISSUE TITLE
ReactiveSeq.range(aNegativeValue, other)

### ISSUE THREAD

**Issue by langzhaozhi** [aol/cyclops-react#177]
```
System.out.println( "IntStream.range(-1,10).sum=" + IntStream.range(-1,10).sum() );
System.out.println( "?This is a bug? ReactiveSeq.range(-1,10).sum=" + ReactiveSeq.range(-1,10).sum() );
System.out.println( "ReactiveSeq.of(-1,0,1,2,3,4,5,6,7,8,9).sum=" + ReactiveSeq.of(-1,0,1,2,3,4,5,6,7,8,9).sum() );
System.out.println( "IntStream.range(0,10).sum=" + IntStream.range(0,10).sum() );
System.out.println( "ReactiveSeq.range(0,10).sum=" + ReactiveSeq.range(0,10).sum() );
System.out.println( "ReactiveSeq.of(0,1,2,3,4,5,6,7,8,9).sum=" + ReactiveSeq.of(0,1,2,3,4,5,6,7,8,9).sum() );
```

ReactiveSeq.range can not start with a negative value

**Comment by johnmcclean-aol** [comment]
You are right, there is an explicit check to confirm the range is 0 or above. This is an oversight / bug. Will fix ASAP.

**Comment by langzhaozhi** [comment]
In ReversingRangeIntSpliterator.java, both the 'index' and 'max' menber variables do not match the constructor's 'start' and 'end' meaning (comparing to JDK IntStream.range implementation). So if the ReversingRangeIntSpliterator class is used in other situation in which the 'index' and the 'max' is just suitable or fit, you may have to consider to use a new class like JDK's

**Comment by johnmcclean-aol** [comment]
Yep. I was thinking about using another field to represent the min value i.e. 

      private final int min;
      private final int max;
      private int index;

      public ReversingRangeIntSpliterator(int min, int max, boolean reverse) {
         super();
         this.min = min-1;
         this.max = max;
         this.reverse = reverse;
         this.index = min;
     }
and then

     if(!reverse){
        	if(index<max && index>min){
        		consumer.accept(index++);
        		return true;
        	}
        }
        if(reverse){
        	if(index>min && index<max){
        		consumer.accept(index--);
        		return true;
        	}
        }

Have not tested it across all scenarios yet, but does work for those I've tested e.g .

       System.out.println( "IntStream.range(-1,10).sum=" + IntStream.range(-1,10).sum() );
       System.out.println( "?This is a bug? ReactiveSeq.range(-1,10).sum=" + ReactiveSeq.range(-1,10).sum() );

**Comment by johnmcclean-aol** [comment]
Fixed on master and ready for release
