### ISSUE TITLE
Misleading example in Javadoc for ListT#lift2()

### ISSUE THREAD

**Issue by smillies** [aol/cyclops-react#178]
The docs show an example where a stream is passed to a function lifted by ListT#list2(). The example has two peculiarities that make it unsuitable as a general guideline: The stream-wrapping list transformer is passed as the first argument, and the other argument contains a singleton list. In the general case, e. g. passing a CompletableFuture containing a two-element list, and having the wrapped stream come second, you'll get a java.lang.IllegalStateException: stream has already been operated upon or closed.

Here's an example that works correctly:

```
 CompletableFuture<List<Integer>> cf = CompletableFuture.supplyAsync(() -> asList(20, 40));
 ListT<Integer> dividends = ListT.of(AnyM.fromCompletableFuture(cf));
 ListT<Integer> divisors = ListT.of(AnyM.ofSeq(asList((asList(2,4)))));
  BiFunction<ListT<Integer>, ListT<Integer>, ListT<Integer>> divide = ListT.lift2(this::divide);
  ListT<Integer> result = divide.apply(dividends, divisors); 
  AnyM<List<Integer>> anyM = result.unwrap();
  CompletableFuture<List<Integer>> completed = anyM.unwrap();
  List<Integer> quotients = completed.join(); 
  assertEquals(asList(10, 5, 20, 10), quotients);
```

The example also highlights the fact how awkward it is to create a monad transformer from a simple list. I am sure there are still other way to do it, but none seems really satisfying.

**Comment by smillies** [comment]
oops, just noticed issue #145 addressing my second point.

**Comment by johnmcclean-aol** [comment]
Yep, they are not easy to use - something I want to address in RC3.

**Comment by johnmcclean-aol** [comment]
Replaced with type safe monad transformers in v2
