### ISSUE TITLE
Remove zip(Seq<U> seq) from Traversable

### ISSUE THREAD

**Issue by johnmcclean-aol** [aol/cyclops-react#188]
This needs to be present on ReactiveSeq and LazyFutureStream for compatibility reasons with jOOλ, but makes less sense than a more general zipStream(Stream<U>) (which also exists), on extended Collections and other Traversables.

**Comment by johnmcclean-aol** [comment]
jOOλ API has 3 methods
    
     zip(Stream<? extends T> other);
     zip(Iterable<? extends T> other);

And zip that accepts a Seq is likely for differentiation for types that implement both Stream and Iterable (e.g. Seq) 


        zip(Seq<? extends T? other);

This works for both  jOOλ and cyclops-react as in both libs extended Stream types are derived from Seq. It may cause issues with other libraries if developers there implement both Stream and Iterable within the same class.

**Comment by johnmcclean-aol** [comment]
Using intersection types doesn't seem to help 

      default <U, X extends Iterable<? extends U> & Stream<? extends U>> Traversable<Tuple2<T, U>> zip(X other)

Bizarrely has the same type erasure as 

     default <U> Traversable<Tuple2<T, U>> zip(Iterable<? extends U> other)

**Comment by lukaseder** [comment]
> And zip that accepts a Seq is likely for differentiation

Indeed. It's a bit unfortunate that `Stream` does not extend `Iterable`. This shouldn't be necessary...

> Bizarrely has the same type erasure as

The reason for this is because an intersection type in Java is a "lie" in terms of byte code. The JVM only supports ordinary types. The first type in the intersection chain is chosen. All other types are erased (apart from potential casts) at compile time.

Anyway, is there anything I can do from the jOOλ side?

**Comment by johnmcclean-aol** [comment]
The only other option I can think of here would be to avoid method overloading and give the methods different names

      zip(Stream<? extends T> other);
      zipIterable(Iterable<? extends T> other);

That way there would be no conflict with either Seq or any other third party type that implements both Iterable and Stream. It would mean just two methods rather than one (or four rather than six because of the overloads that accept a zipper funciton).

What do you think?

**Comment by lukaseder** [comment]
I have thought about that. It's the same story as always with overloading. Overloading is nice for API consumers but causes issues for API producers. I personally don't really like putting the overload type in the name of the "overloaded" method. In that case, it would be better to simply provide a simpler `stream(Iterable)` method...

**Comment by johnmcclean-aol** [comment]
Is stream(Iterable) a static method to create a Stream from an Iterable in that case? I.e. 
   
      zip(stream(Arrays.asList(10,20,30)));

The overloaded alternative is definitely easier for most consumers to use.

Maybe static (as) iterable / stream methods could be used in conjunction with the overloaded methods, to coerce a type to a single target.

@amaembo's StreamEx library implements Stream and Iterable but it could be used with something like 


       zip(asStream(StreamEx.of("a","b","c")));

I'm thinking I probably should also add

       zip(Publisher<T> publisher)

**Comment by lukaseder** [comment]
> The overloaded alternative is definitely easier for most consumers to use.

Perhaps...

> I'm thinking I probably should also add

But your traversable extends `Publisher` too. You're entering dangerous waters, here :)

**Comment by johnmcclean-aol** [comment]
> But your traversable extends Publisher too. You're entering dangerous waters, here :)

Eek! You are right, I would have to add zip(Traversable<T> other) too :)

Static method approach can help here instead.

**Comment by johnmcclean-aol** [comment]
Merged in https://github.com/aol/cyclops-react/pull/232

**Comment by johnmcclean-aol** [comment]
Api combo of zip(Iterable) zip(Seq) zip(Stream) used. Other zip methods standardized to a consistent form also.
