### ISSUE TITLE
AnyMValue should override flatMapFirst and return AnyMValue

### ISSUE THREAD

**Issue by johnmcclean-aol** [aol/cyclops-react#193]

**Comment by johnmcclean-aol** [comment]
flatMapFirst should also only take the first value and it does not.

System.out.println(AnyM.fromMaybe(Maybe.just(10)).flatMapFirst(i->AnyM.fromList(ListX.of(i,20,30))).stream().toList());

**Comment by wyang14** [comment]
This doesn't happen for Streams, it only happens for Lists System.out.println(AnyM.fromMaybe(Maybe.just(10)).flatMapFirst(i->AnyM.fromStream(ReactiveSeq.of(i,20,30))).stream().toList());

**Comment by johnmcclean-aol** [comment]
Merged in https://github.com/aol/cyclops-react/pull/221
