### ISSUE TITLE
Typo in ListT#fromIterablListue

### ISSUE THREAD

**Issue by smillies** [aol/cyclops-react#196]
I guess that should be "fromIterableValue" ?

-- Sebastian

**Comment by johnmcclean-aol** [comment]
I think just fromIterable.

Thanks a million for reporting this.

Have you found the new monad transformers any easier to use?

**Comment by smillies** [comment]
No, I don't think. There already is a LIstT#fromIterable that does something different.

And yes, it's less confusing when you don't need to explicitly mention AnyM, for example I can just write `ListT.fromFuture(cf);` where previously I had `ListT.of(AnyM.fromCompletableFuture(cf));`

BTW, my old lifting example (see below, not using the new transformers) now generates java.util.concurrent.CompletionException: java.lang.IllegalStateException: stream has already been operated upon or closed. 

```
@Test
public void asyncFutureWithList() {
    CompletableFuture<List<Integer>> cf = CompletableFuture.supplyAsync(() -> asList(20, 40));
    ListT<Integer> dividends = ListT.of(AnyM.fromCompletableFuture(cf));
    ListT<Integer> divisors = ListT.of(AnyM.ofSeq(asList((asList(2,4)))));
    BiFunction<ListT<Integer>, ListT<Integer>, ListT<Integer>> divide = ListT.lift2(this::divide);
    ListT<Integer> result = divide.apply(dividends, divisors); 
    AnyM<ListX<Integer>> anyM = result.unwrap();  // note the ListX
    CompletableFuture<List<Integer>> completed = anyM.unwrap();
    List<Integer> quotients = completed.join(); 
    assertEquals(asList(10, 5, 20, 10), quotients);
}
```

Is that a bug or intentional? Not that I'd write such code any more, now that there is ListT#fromIterable.

Sebastian

**Comment by johnmcclean-aol** [comment]
I think it's a bug. AnyM.ofSeq is untyped and somewhat unsafe. It should attempt to convert stuff it doesn't understand into a format it does (Iterable into a Stream for example), but cyclops-react has adapaters / comprehenders for Lists so they should never automatically get converted like this. 

I'll log a bug and add this as a test. 

Thanks again!

**Comment by smillies** [comment]
Another incarnation of the same bug shows up in a modified version of your recent post on the JOOQ blog (nice article, by the way, it succeeds in creating an overall feel of the purpose and versatility of the whole enterprise).

The following throws the exception:
```
@Test
public void anyMListConversion() {
  AnyMSeq<Integer> wrapped = AnyM.fromList(asList(1, 2, 3, 4, 5));

  Eval<Integer> lazyResult = wrapped
          .map(i -> i * 10)
          .lazyOperations() 
          .reduce(50, (acc, next) -> acc + next);
     
  assertSame(200, lazyResult.get().intValue());
}
```
Wrapping the list with `AnyM.ofSeq(asList(1, 2, 3, 4, 5))` is also unsuccessful. It works when one interpolates an iterable, as you do in your post, or with the following variants:
`AnyM.fromIterable(asList(1, 2, 3, 4, 5))` or  `AnyM.ofSeq(ReactiveSeq.fromIterable(asList(1, 2, 3, 4, 5)))`

**Comment by johnmcclean-aol** [comment]
Yes, this needs fixed. I've come across a number of other ways to replicate this also.

The ListComprehender and SetComprehender convert from the org collection type into a Stream (during map / filter / flatMap operations). I've removed these conversions locally from the ListComprehender and will do the same for the SetComprehender ASAP. It was an oversight on my part, I forgot they were doing that. Then there should no conversions at all for Lists / Sets inside the AnyM wrapper.

**Comment by johnmcclean-aol** [comment]
Thanks for your kind comments about the article too :)

**Comment by johnmcclean-aol** [comment]
This is fixed on Master, should be released soon.
