### ISSUE TITLE
blocking transfer queue does not slow producing stream?

### ISSUE THREAD

**Issue by johnmcclean-aol** [aol/cyclops-react#204]
Reported by @the-james-burton here - https://github.com/aol/cyclops/issues/198. Fixed for RC4, but in cyclops-react, so this is a better place to track it.

**Comment by the-james-burton** [comment]
Cool... will double check it when you release RC4 to maven central.

**Comment by johnmcclean-aol** [comment]
Merged in https://github.com/aol/cyclops-react/pull/215

This also impacts HotStreams generated via schedule will open up a new issue for this, as I think BlockingQueue's should also apply backpressure to scheduling.

**Comment by johnmcclean-aol** [comment]
Should use put for blocking Queue.

**Comment by johnmcclean-aol** [comment]
Fixed in https://github.com/aol/cyclops-react/pull/234
