### ISSUE TITLE
ReactiveSeq 'retry' does not backoff

### ISSUE THREAD

**Issue by the-james-burton** [aol/cyclops-react#220]
Hi John, I might have another one for you, have a look at this...

Javadoc for the retry function...

>Retry a transformation if it fails. Default settings are to retry up to 7 times, with an doubling backoff period starting @ 2 seconds delay before retry.

Now let's test it...

```java
  @Test
  public void testRetryBackoff() {
    logger.info(TestUtils.getMethodName());

    List<Integer> retry = ReactiveSeq.of(1, 2, 3, 4, 5, 6, 7, 8)
        .retry(i -> TestUtils.alwaysThrowException(i))
        .toList();

    logger.info("retry : {}", retry);
  }
```

It does try seven times as per the default, but I don't see a back off in the timings. The 'failed' log is from the `alwaysThrowException` function...

> 2016-05-27 18:28:56,696  INFO - [      main] c.r.StreamsTest                : testRetryBackoff
> 2016-05-27 18:28:56,828  INFO - [      main] c.r.TestUtils                  : 1: failed
> 2016-05-27 18:28:56,834  INFO - [      main] c.r.TestUtils                  : 1: failed
> 2016-05-27 18:28:56,834  INFO - [      main] c.r.TestUtils                  : 1: failed
> 2016-05-27 18:28:56,834  INFO - [      main] c.r.TestUtils                  : 1: failed
> 2016-05-27 18:28:56,834  INFO - [      main] c.r.TestUtils                  : 1: failed
> 2016-05-27 18:28:56,834  INFO - [      main] c.r.TestUtils                  : 1: failed
> 2016-05-27 18:28:56,834  INFO - [      main] c.r.TestUtils                  : 1: failed

When I try to specify values, it respects the number, but not the time...

```java
  @Test
  public void testRetryBackoff() {
    logger.info(TestUtils.getMethodName());

    List<Integer> retry = ReactiveSeq.of(1, 2, 3, 4, 5, 6, 7, 8)
        .retry(i -> TestUtils.alwaysThrowException(i), 5, 100, TimeUnit.MILLISECONDS)
        .toList();

    logger.info("retry : {}", retry);
  }
```

> 2016-06-01 07:33:09,767  INFO - [      main] c.r.StreamsTest                : testRetryBackoff
> 2016-06-01 07:33:09,879  INFO - [      main] c.r.TestUtils                  : 1: failed
> 2016-06-01 07:33:09,883  INFO - [      main] c.r.TestUtils                  : 1: failed
> 2016-06-01 07:33:09,884  INFO - [      main] c.r.TestUtils                  : 1: failed
> 2016-06-01 07:33:09,884  INFO - [      main] c.r.TestUtils                  : 1: failed
> 2016-06-01 07:33:09,884  INFO - [      main] c.r.TestUtils                  : 1: failed

**Comment by johnmcclean-aol** [comment]
Excellent - thanks for reporting.  You can submit your tests as a PR if you'd like too.

**Comment by johnmcclean-aol** [comment]
Fixed in https://github.com/aol/cyclops-react/pull/243

**Comment by the-james-burton** [comment]
Awesome, thanks John! I'll give RC4 a go asap...
