### ISSUE TITLE
FluentFunctions.memoize(Cacheable cache) don't use cache.

### ISSUE THREAD

**Issue by earlzero** [aol/cyclops-react#246]
It is expected that memoization will use `cache`, but internally it use new ConcurrentHashMap.

Following test fails

    @Test
    public void memoizeWithCache() throws InterruptedException {
        
        Cache<Object, Integer> cache = CacheBuilder.newBuilder()
                .maximumSize(1)
                .expireAfterWrite(1, TimeUnit.SECONDS)
                .build();
        
        int[] requests = new int[1];
        
        Function<Integer, Integer> addOne = i -> { 
            requests[0]++;
            return i + 1;
        };
        Function fn = FluentFunctions.of(addOne).name("myFunction")
                .memoize((key, f) -> cache.get(key, () -> f.apply(key)));

        fn.apply(10);
        fn.apply(10);
        
        Thread.sleep(2000);
        
        fn.apply(10);

        assertEquals(2, requests[0]);
        
    }

Code is based on https://github.com/aol/cyclops-react/blob/master/user-guide/lambdas.adoc#error-and-recovery (Example 2)

**Comment by johnmcclean-aol** [comment]
Good spot.

**Comment by johnmcclean-aol** [comment]
Merged via https://github.com/aol/cyclops-react/pull/247
