### ISSUE TITLE
fromIterableAsync in SimpleReactStream should have a more liberal generic signature

### ISSUE THREAD

**Issue by johnmcclean-aol** [aol/cyclops-react#257]
public <U> SimpleReactStream<U> fromIterableAsync(final Iterable<Supplier<U>> actions)

Should be replaced with 

       public <U> SimpleReactStream<U> fromIterableAsync(final Iterable<? extends Supplier<U>> actions) 

Similar apis should be checked also.

**Comment by wyang14** [comment]
PR https://github.com/aol/cyclops-react/pull/259 created for this issue.
