### ISSUE TITLE
parallel not working?

### ISSUE THREAD

**Issue by saschaarthur** [aol/cyclops-react#283]
hello,

somehow the main thread is solving the queue, so it doesnt work out that stream is running in parallel:

Maybe its my issue and someone can help me out?
```

        com.aol.cyclops.data.async.Queue<Integer> queue = QueueFactories.<Integer>boundedQueue(30).build();
        Thread t = new Thread(() -> {
            for(int i=0; i < 100;i++)
            {
                queue.offer(i);
            }
            queue.close();
        });
        t.start();
        queue.stream().parallel().forEach(e ->
        {
            System.out.println(Thread.currentThread().getName() + " -> " + e);
        });
```

```

main -> 0
main -> 1
main -> 2
main -> 3
main -> 4
main -> 5
main -> 6
main -> 7
main -> 8
main -> 9
main -> 10
main -> 11
main -> 12
main -> 13
main -> 14
main -> 15
main -> 16
main -> 17
main -> 18
main -> 19
main -> 20
main -> 21
main -> 22
main -> 23
main -> 24
main -> 25
main -> 26
main -> 27
main -> 28
main -> 29
main -> 30
main -> 31
main -> 32
main -> 33
main -> 34
main -> 35
main -> 36
main -> 37
main -> 38
main -> 39
main -> 40
main -> 41
main -> 42
main -> 43
main -> 44
main -> 45
main -> 46
main -> 47
main -> 48
main -> 49
main -> 50
main -> 51
main -> 52
main -> 53
main -> 54
main -> 55
main -> 56
main -> 57
main -> 58
main -> 59
main -> 60
main -> 61
main -> 62
main -> 63
main -> 64
main -> 65
main -> 66
main -> 67
main -> 68
main -> 69
main -> 70
main -> 71
main -> 72
main -> 73
main -> 74
main -> 75
main -> 76
main -> 77
main -> 78
main -> 79
main -> 80
main -> 81
main -> 82
main -> 83
main -> 84
main -> 85
main -> 86
main -> 87
main -> 88
main -> 89
main -> 90
main -> 91
main -> 92
main -> 93
main -> 94
main -> 95
main -> 96
main -> 97
main -> 98
main -> 99
```

**Comment by johnmcclean-aol** [comment]
Thanks for reporting this.

The stream() method in cyclops-react types always returns a ReactiveSeq instance. This extends JDK Stream via jOOλ Seq. The convention in jOOλ which we follow in cyclops-react is that ReactiveSeq / Seq is sequential only (so it isn't possible to switch between types via parallel / sequential). See jOOλ issue - https://github.com/jOOQ/jOOL/issues/130

The Javadoc for Queue#stream is misleading (it was probably written when it was possible to switch between parallel and sequential operations in the ReactiveSeq type).

We can use (a new) jdkStream() method in the Queue class to return a standard JDK Stream that will support parallel & sequential operation. If you want to implement it, it would probably look very similar to the current stream() implementation, without decorating the JDK Stream with the ReactiveSeq interface.

E.g. The stream() method 

```java
      public ReactiveSeq<T> stream() {
        listeningStreams.incrementAndGet(); //assumes all Streams that ever connected, remain connected
        return ReactiveSeq.fromStream(closingStream(this::get, new AlwaysContinue()));
    }
 
```

a jdkStream() method

```java
       public Stream<T> jdkStream() {
         listeningStreams.incrementAndGet(); 
         return closingStream(this::get, new AlwaysContinue());
     }
```

**Comment by saschaarthur** [comment]
thanks for figuring this out. I tried to extend the queue but it seems like the most stuff is private instead of protected, so i will wait for 1.0

**Comment by johnmcclean-aol** [comment]
Merged on master.
