### ISSUE TITLE
Enhanced eval stream() method

### ISSUE THREAD

**Issue by johnmcclean** [aol/cyclops-react#292]
Provide alternative stream generating methods that allow a termination criteria such as

```
      streamUntil
      streamWhile
      streamUntil(time)
```

**Comment by johnmcclean-aol** [comment]
default ReactiveSeq<T> streamUntil(Predicate<? super T> pred){
        return ReactiveSeq.generate(this::get)
                   .takeUntil(pred);
    }
    default ReactiveSeq<T> streamWhile(Predicate<? super T> pred){
        return ReactiveSeq.generate(this::get)
                   .takeWhile(pred);
    }

**Comment by johnmcclean** [comment]
Can be added to Function0 instead.

**Comment by johnmcclean** [comment]
Merged (added to Eval)
