### ISSUE TITLE
Javadoc conversion methods on com.aol.cyclops.types.Value

### ISSUE THREAD

**Issue by johnmcclean-aol** [aol/cyclops-react#313]
Methods such as 

     default ListX<T> toListX()

etc need a very short, simple but explanatory javadoc comment

**Comment by LauraLaureus** [comment]
Did you assign this to somebody? Do you need the javadoc only for data structures?

**Comment by johnmcclean-aol** [comment]
Hey Laura,

It's still available if you'd like. Simple javadoc for all methods in Value that don't override a method from a subclass would be great!

Thanks,
John

**Comment by LauraLaureus** [comment]
I'm on it ;)

**Comment by johnmcclean-aol** [comment]
Awesome - thanks Laura!

**Comment by LauraLaureus** [comment]
I have just done the pull request

**Comment by johnmcclean-aol** [comment]
Implemented in https://github.com/aol/cyclops-react/pull/331

Released.
