### ISSUE TITLE
Add derive4j HKT interfaces to cyclops-react datastructures

### ISSUE THREAD

**Issue by johnmcclean-aol** [aol/cyclops-react#347]
Make integration with any libraries that support them (such as HighJ) simpler.

Also in cyclops we could create a more general integration library that maps between HKT witness types and the underlying type it witnesses (e.g. from List.µ to List). Which would allow us to retrofit HigherKindedType support to any library - even those without inner witness types defined on their datastructures (i.e. Functional Java, Javaslang etc), and provide implementations of HKT based Type Classes by plumbing the mappings between unimplemented methods and the appropriate method references (for map / bind / unit etc).

**Comment by johnmcclean-aol** [comment]
See https://github.com/aol/cyclops/issues/228, moved out derive4j HKT integration until 1.1.0 - to make sure there are no unforeseen impacts of introducing the annotation processor.

Will introduce a less strict 'Higher' and Higher2 type in 1.0.2 which can be used in cyclops-typeclasses to integrate 3rd party libraries such as Functional Java, Javaslang, Reactor & RxJava.

**Comment by johnmcclean-aol** [comment]
The infrastructure has been put in place in MI1. There seems to be some conflict between derive4j and the Lombok pluin in IntelliJ will log an issue and work with the derive4j team to resolve for MI2.

**Comment by johnmcclean-aol** [comment]
Closing as non-ascii class names cause issues in AWS.

**Comment by jbgi** [comment]
That's interesting... Do you have a link to a description of the issue with non-ascii class name?

**Comment by johnmcclean-aol** [comment]
Hey @jbgi - here is the issue logged by one of our Engineers (https://github.com/aol/cyclops-react/issues/641) . The inner class µ doesn't get loaded into the JVM in AWS. I think this is the same bug that Javaslang users experienced with a class named λ.

We've mostly been using Docker so didn't see (it only occurs on bare metal EC2 instances).

If you switch to a different naming convention we can reconsider (also would need to get smooth IntelliJ / lombok integration - I'm not sure which one is causing the need to use clean - this will affect application engineers using cyclops.)
