### ISSUE TITLE
ReactiveSeqImpl.subscribe(Subscriber) assumes non-concurrent requesting

### ISSUE THREAD

**Issue by akarnokd** [aol/cyclops-react#395]
The Reactive-Streams specification is a bit vague on this but my experience is that one should not assume `request()` comes synchronously from the consumer of `onNext`.

I'd like to contribute a proper RS iterator logic but I'm not sure which branch to target and how to deal with the 400+ compilation error I get from Eclipse when checking out master. (IntelliJ 2016.2.5 doesn't seem to be better).

**Comment by johnmcclean-aol** [comment]
Thanks David, target master (branches need cleaned up). You need to install Lombok. https://projectlombok.org/features/index.html

You can normally download the jar, run it and point it at your eclipse instance and it will update the confit itself.

**Comment by johnmcclean-aol** [comment]
I think we can use the one you wrote in RSC, that looks pretty solid to me : https://github.com/reactor/reactive-streams-commons/blob/master/src/main/java/rsc/publisher/PublisherIterable.java and I think that is also a good dependency to add.

**Comment by akarnokd** [comment]
Yes, strip the fusion and tracking features and it should work nicely.

**Comment by johnmcclean-aol** [comment]
@akarnokd Is it ok to copy that one into cyclops-react? I don't see reactive-streams-commons in mvn central to add as a dependency.

**Comment by akarnokd** [comment]
Yes, just copy in the code, no need to include the full library.

**Comment by johnmcclean-aol** [comment]
Merged
