### ISSUE TITLE
Bug in LimitLastOneSpliterator

### ISSUE THREAD

**Issue by johnmcclean** [aol/cyclops-react#447]
The following code should return 4 but instead returns -1. This is because LimitLastOneSpliterator doesn't terminate the tryAdvance cycle correctly (and singleOptional presumes more values are available).

```java
ReactiveSeq.of(1, 2, 3, 4)
           .takeRight(1)
           .singleOptional()
           .orElse(-1)
```

Since 1.0.5

**Comment by johnmcclean-aol** [comment]
Fixed for v2.x in https://github.com/aol/cyclops-react/pull/451
