### ISSUE TITLE
FluentFunctions retry does not sleep when exceptions occur

### ISSUE THREAD

**Issue by jlorenzen** [aol/cyclops-react#475]
I'm playing around with cyclops to perform some basic retry functionality and it appears the `retry` method doesn't sleep properly when an exception occurs.

Here is my intellij idea snippet:
```java
import cyclops.function.FluentFunctions;

class FluentTest {
    public static void main(String[] args) {
        final Test test = new Test();
        FluentFunctions.checkedExpression(test::getName)
                .retry(3, 5000)
                .apply("bob");
    }

    static class Test {
        private static int failed = 0;

        public void getName(final String name) {
            if (failed < 2) {
                failed++;
                System.out.println("error");
                throw new RuntimeException("error");
            }
            System.out.println("name = " + name);
        }
    }
}

// output
error
error
name = bob
```

This should take around 10 seconds to finish but it finishes immediately. I'm using dependency version: `com.aol.simplereact:cyclops-react:2.0.0-MI2`.

Looking at the code in `retry`, it would seem this line:
```java
ExceptionSoftener.softenRunnable(() -> Thread.sleep(sleep.get()));
```
Would need to change to something like:
```java
final Runnable r = ExceptionSoftener.softenRunnable(() -> Thread.sleep(sleep.get()));
r.run(); // runs synchronously
```

**Comment by johnmcclean-aol** [comment]
@jlorenzen Awesome bug report! Looks like you are correct the runnable is never called. Do you wan t to submit a PR for this issue (you've done all the hard work so should get the credit for the fix :) ). Or I can change it if not.

**Comment by jlorenzen** [comment]
Yeah I don't mind. A test might be kind of hard, but I'll try to write a failing one before I fix it.

**Comment by jlorenzen** [comment]
@johnmcclean-aol PR is ready for review #476
