### ISSUE TITLE
crossJoin operator missing from ReactiveSeq

### ISSUE THREAD

**Issue by Ramblurr** [aol/cyclops-react#512]
The java doc and manual indicate that `ReactiveSeq` should have a `crossJoin` method, but it is no where to be found in 2.0.0-MI1

Was it removed?

**Comment by johnmcclean-aol** [comment]
Hey Ramblur,

Looks like it is missing from ReactiveSeq in the refactoring of 2.0.0-X but is still on FutureStream. Let's get it added back in.

**Comment by johnmcclean-aol** [comment]
This code is equivalent to crossJoin 

```java
     ReactiveSeq.of(1,2,3).forEach2(a->ReactiveSeq.of(4,5,6), Tuple::tuple);
```

But is potentially more powerful, as the ReactiveSeq forming a cartesian product with the initial ReactiveSeq has access to each element in turn, and the BiFunction parameter allows more flexible combinations (than just Tuple creation).

That said, the syntax of ```java crossJoin(Stream)``` that results in a ```javaReactiveSeq<Tuple>``` is simpler and less verbose.

**Comment by Ramblurr** [comment]
What about `.combinations(2)`, how does that compare to `forEach2()` or `crossJoin`?

**Comment by johnmcclean-aol** [comment]
It's similar but can only form a cross join over one Stream. I think this is the equivalent code with forEach2 (have not tested to be 100%) 

```java
ReactiveSeq.of(1,2,3).forEach2(a->ReactiveSeq.of(1,2,3), ReactiveSeq::of);
```

**Comment by johnmcclean-aol** [comment]
You can use the same technique with Java 8 Streams via the forEach2 method on the Streams class by the way.

**Comment by Ramblurr** [comment]
In my case `.combinations(2)` is sufficient as I only need the unique pair elements (not the permutations) in the one stream. Nice to know that crossJoin is coming back though.

I like the `forEach2` example, very powerful.
