### ISSUE TITLE
Batching works in an unexpected way when using futureStream

### ISSUE THREAD

**Issue by JesusMetapack** [aol/cyclops-react#515]
0
down vote
favorite
	

I am trying to use cyclops-react to batch the elements from a queue, based on size, but also on time, so it doesn't block when there are no elements

Maybe the functionality is not what I expected or I am doing something wrong

The complete code (Groovy) is like this with the producer in another thread:
```
            Queue<String> queue = QueueFactories.<String>unboundedQueue().build();
    new Thread({
        while (true) {
            sleep(1000)
            queue.offer("New message " + System.currentTimeMillis());
        }
    }).start();

    StreamSource.futureStream(queue, new LazyReact(ThreadPools.queueCopyExecutor))
            .groupedBySizeAndTime(10,500,TimeUnit.MILLISECONDS)
            .forEach({i->println(i + " Batch Time: ${System.currentTimeMillis()}")})
```

The output is:
```
    [New message 1487673650332,  Batch Time: 1487673651356]
    [New message 1487673651348, New message 1487673652352,  Batch Time: 1487673653356]
    [New message 1487673653355, New message 1487673654357,  Batch Time: 1487673655362]
    [New message 1487673655362, New message 1487673656364,  Batch Time: 1487673657365]
```

But I was expecting one element in each batch since the delay between elements offered is 1 second but the batching is every half a second

Also I tried with an asynchronous stream (Groovy code):

```
    Queue<String> queue = QueueFactories.<String>unboundedQueue().build();
    StreamSource.futureStream(queue, new LazyReact(ThreadPools.queueCopyExecutor))
            .async()
            .groupedBySizeAndTime(10, 500,TimeUnit.MILLISECONDS)
            .peek({i->println(i + "Batch Time: ${System.currentTimeMillis()}")}).run();

    while (true) {
        queue.offer("New message " + System.currentTimeMillis());
        sleep(1000)
    }
```

Again, it only batches every 2 seconds sometimes waiting for two elements per batch, even if the timeout in the batch is half second:

```
    [New message 1487673877780, Batch Time: 1487673878819]
    [New message 1487673878811, New message 1487673879812, Batch Time: 1487673880815]
    [New message 1487673880814, New message 1487673881819, Batch Time: 1487673882823]
    [New message 1487673882823, New message 1487673883824, Batch Time: 1487673884828]
    [New message 1487673884828, New message 1487673885831, Batch Time: 1487673886835]
```

I did a third experiment with a non future non lazy stream, and this time it worked.

 ```
Queue<String> queue = QueueFactories.<String>unboundedQueue().build();
    new Thread({
        while (true) {
            sleep(1000)
            queue.offer("New message " + System.currentTimeMillis());
        }
    }).start();

    queue.stream()
            .groupedBySizeAndTime(10,500,TimeUnit.MILLISECONDS)
            .forEach({i->println(i + " Batch Time " + System.currentTimeMillis())})
```

Result:

 ```
   [New message 1487673288017, New message 1487673289027,  Batch Time , 1487673289055]
    [New message 1487673290029,  Batch Time , 1487673290029]
    [New message 1487673291033,  Batch Time , 1487673291033]
    [New message 1487673292037,  Batch Time , 1487673292037]
```

Why is the behaviour of the batching seems to be wrong when you use a future stream?

**Comment by johnmcclean-aol** [comment]
Many thanks for the awesome bug report!

Testing against v2 the FutureStream impl is pulling values from the initial Queue 2 at a time for some reason (this is certainly bug).

**Comment by johnmcclean-aol** [comment]
So it appears to be behaving functionally as expected (but is underperforming), so I still think there are improvements to be made.

The reason they get batched into 2s for FutureStreams (at least in v2 of cyclops-react I will also check v1), is down to the overhead of transfering data between 2 Queues via a Future. I think in this case that transfer is unneccessary.

What is happening is this.

1. You have a Queue you are pushing values onto.
2. StreamSource.futureStream also creates a Queue.
3. Futures are used to transfer data from your Queue onto the internal one created via StreamSource
4. This additional overhead / task scheduling factors is large enough that we wind up with two values in our group.

When we do the grouping we check if any upstream values are present, when the next upstream value arrives we check to see if we are within our alloted time and size bounds. If value arrives within 500ms of the previous one we will ask for another value from the Queue and wait until one arrives. The additional overhead doing the unnecessary transfer means we eat into the 1 sec delay between values and there is a good chance the first value in any batch arrives within the 500ms limits, causing us to request another - adding two values to our batch / group instead of one.

As a work around this also works

```java
 queue.stream()
                .groupedBySizeAndTime(10,500,TimeUnit.MILLISECONDS)
                .futureStream(new LazyReact())
                .forEach(i-> {
                    System.out.println(i + " Batch Time:" + System.currentTimeMillis());
                });
```

**Comment by johnmcclean-aol** [comment]
The solution is to create FutureStream directly from the user supplied Queue in StreamSource.

**Comment by JesusMetapack** [comment]
The work around you suggested didn't work for me..the forEach at the end of the stream doesn't create an asynchronous task and it blocks

I had to use it this way
```
        queue.stream()
                            .groupedBySizeAndTime(batchSize, batchTimeoutMillis, TimeUnit.MILLISECONDS)
                            .futureStream(new LazyReact(ThreadPools.getSequential()))
                            .async()
                            .peek(this::executeBatch)
                            .run();
```

**Comment by JesusMetapack** [comment]
Nevetheless there is still a small issue. I am using now the User supplied queue as you suggested:

When  I add just one element to the queue immediately after I call run(), that element never gets batched.. Only after the asynchronous stream has finished starting its Executor thread, and I add more elements to the queue, then it gets batched 

I had this issue because in my unit test I only had one element added and it never got batched

If I add a Sleep long enough after the queue.stream().groupedBySizeAndTime()........run(), and then I add an element to the queue.. then it gets batched

**Comment by johnmcclean-aol** [comment]
Which version are you using?

**Comment by JesusMetapack** [comment]
2.0.0 MI4

**Comment by johnmcclean-aol** [comment]
Thanks! 

When an element is added immediately after Stream construction it is ingested into the group / batch immediately and the Stream asks for another one from the Queue (and waits until it gets it). It will then get batched with the next element added to the queue.

The Queue class contains a streamBatch method so it would be possible to use that method to build time/ size based grouping that would timeout and continue processing after X ms (or other time units). I'll put together some example code to do that tomorrow.

**Comment by johnmcclean-aol** [comment]
It probably makes sense to add this type of functionality as an easy to use operator on Queue.

I think this should do what you want, max batch size of 10 or 500ms with timeout rather than waiting for the next value.

```java
Queue<String> queue = QueueFactories.<String>unboundedQueue().build();
        new Thread(()->{
            for(int i=0;i<10;i++){

                queue.offer("New message " + i);
                sleep(10000);
            }
            queue.close();
        }).start();

        long toRun = TimeUnit.MILLISECONDS.toNanos(500l);

        queue.streamBatch(new Subscription(), source->{

            return ()->{
                List<String> result = new ArrayList<>();


                   long start = System.nanoTime();

                       while (result.size() < 10 && (System.nanoTime() - start) < toRun) {
                           try {
                               String next = source.apply(1l, TimeUnit.MILLISECONDS);
                               if (next != null) {
                                   result.add(next);
                               }
                           }catch(Queue.QueueTimeoutException e){

                           }


                       }

                    if(result.size()>0){
                        System.out.println("Result " +  result);
                    }


                start=System.nanoTime();


                return result;
            };
        }).filter(l->l.size()>0)
          .futureStream(new LazyReact(ThreadPools.getSequential()))
                .async()
                .peek(System.out::println)
                .run();
```

**Comment by JesusMetapack** [comment]
Hi. Thanks
I appreciate that with that level of control I can achieve what I need. Thanks for the example. I was looking at the streamBatch method but didn't find any example.

But I still think that the other way is more elegant, and I would have thought that both, the sync queue.stream and the async queue.futureStream should behave equally in terms of the results and they should be interchangeable. Not sure if other people agree

**Comment by johnmcclean-aol** [comment]
You are right it's definitely a bug. 

The part above that describes the solution are the internal changes required so the behaviour is the same (of course as users externally we can do something similar, but there is a fix required).  Apologies if that wasn't clear.

**Comment by johnmcclean-aol** [comment]
StreamSource.futureStream creates it's own Queue (rather than reusing the users) which results in needless inefficient data transfer via Futures between the User's Queue and StreamSources, that additional overhead results in the inconsistent behaviour between FutureStreams and ReactiveSeqs.

**Comment by JesusMetapack** [comment]
Thanks a lot for your help

**Comment by johnmcclean-aol** [comment]
You are welcome. I'll add some separate issues for convenience methods on Queue, which have knowledge of the Queue and can thus do an accurate time out there. Should allow for a more elegant solution.

**Comment by johnmcclean-aol** [comment]
Merged on master
