### ISSUE TITLE
Predicates.sample missing

### ISSUE THREAD

**Issue by Ramblurr** [aol/cyclops-react#522]
[This wiki page](https://github.com/aol/cyclops-react/wiki/Take,-Skip-and-Sample) indicates that there should be a `Predicates.sample` function, however in `cyclops-react:2.0.0-MI4` it seems to be missing.

**Comment by johnmcclean-aol** [comment]
Looks like that was removed a long time ago (pre 1.0.0). Both SimpleReact and cyclops (separate projects that were merged) had a Predicates class, I guess this got dropped in the merge. It would have been present in the SimpleReact version.

Sample probably should have at least a couple of overloaded variants

* sample(long time,TimeUnit unit) - take one element per timeperiod
* sample(long elements, long time,TimeUnit unit) - take specified number of elements (on arrival) per time period)

**Comment by Ramblurr** [comment]
It would also be nice to collect a random sample. 

`sample(double percent)` - take percent% of elements. Would work on infinite or finite streams.

**Comment by johnmcclean-aol** [comment]
Like the original version did :) 
I should have read the wiki better. Yes that makes sense too.

**Comment by Ramblurr** [comment]
I didn't realize that cyclops-react was the merger of different projects! That definitely explains some of the schizophrenia in the documentation I've seen.

**Comment by johnmcclean-aol** [comment]
A lot of the documentation needs to be upgraded. 2.x isn't really covered yet at all. Do you have any glaring examples? We can track them in an issue.

**Comment by johnmcclean-aol** [comment]
Going to restore the original and also implement sampling by time for the 2.0.0-MI5 release, if we feel we need more sampling predicates we can revisit for future releases.

**Comment by johnmcclean-aol** [comment]
Merged on master
