### ISSUE TITLE
1.x Issue : Combining flatMap with recover is dropping entries

### ISSUE THREAD

**Issue by jijisv** [aol/cyclops-react#523]
Test:
```java
@Test
public void testRecoverWithMap1() {
    Map<String, List<String>> dataMap = new HashMap<>();
    dataMap.put("k1", Arrays.asList("1", "two", "3"));
    dataMap.put("k2", Arrays.asList("four", "5"));
    dataMap.put("k3", Arrays.asList("6"));

    assertThat(ReactiveSeq.fromIterable(dataMap.entrySet())
                            .flatMap(e -> e.getValue().stream())
                            .map(Integer::valueOf)
                            .recover(e -> -1)
                            .toList(), equalTo(Arrays.asList(1, -1, 3, -1, 5, 6)));
}
```
Output: 
```
java.lang.AssertionError: 
Expected: <[1, -1, 3, -1, 5, 6]>
     but: was <[-1, -1, 6]>
```
You can see that the `recover` is dropping values from the list when there is an error with `map(Integer::valueOf)`

Found this issue with 1.x and same test working as expected in 2.x.

**Comment by jijisv** [comment]
I did some digging today and the issue is not with recovery operator but with jdk Stream's `flatMap` operator not being executed in lazy/pull mechanism.

Below code is from jdk `ReferencePipeline`
```java
    @Override
    public final <R> Stream<R> flatMap(Function<? super P_OUT, ? extends Stream<? extends R>> mapper) {
        Objects.requireNonNull(mapper);
        // We can do better than this, by polling cancellationRequested when stream is infinite
        return new StatelessOp<P_OUT, R>(this, StreamShape.REFERENCE,
                                     StreamOpFlag.NOT_SORTED | StreamOpFlag.NOT_DISTINCT | StreamOpFlag.NOT_SIZED) {
            @Override
            Sink<P_OUT> opWrapSink(int flags, Sink<R> sink) {
                return new Sink.ChainedReference<P_OUT, R>(sink) {
                    @Override
                    public void begin(long size) {
                        downstream.begin(-1);
                    }

                    @Override
                    public void accept(P_OUT u) {
                        try (Stream<? extends R> result = mapper.apply(u)) {
                            // We can do better that this too; optimize for depth=0 case and just grab spliterator and forEach it
                            if (result != null)
                                result.sequential().forEach(downstream);
                        }
                    }
                };
            }
        };
    }
```

You can see the after invoking the flatmap operation (`mapper.apply(u)` in `accept` method), it is sequentially iterating over elements and invoking the downstream pipeline.

So, in our eg, the flat map operation will return a stream per each value entry Hashmap, and the flatmap will call the downstream pipeline (`map` operation in our eg) for each value in the stream. For the entry `dataMap.put("k1", Arrays.asList("1", "two", "3"));`, the second call in the iteration will fail with NumberFormatException and that will be rolled up all the way to the recovery operator and the rest of values in the stream will be ignored. The recovery operator will recover the exception to -1 and since the rest of the stream is ignored the `ReferencePipeline` will copy only -1 to the buffer. Thats the reason we are seeing only one value (-1) for all the sub list which are failed in converting to Long.

Here are some links which highlight the issue.
http://stackoverflow.com/questions/29229373/why-filter-after-flatmap-is-not-completely-lazy-in-java-streams
https://bugs.openjdk.java.net/browse/JDK-8075939

**Comment by johnmcclean-aol** [comment]
Awesome work @jijisv !!  

I've changed the label from Bug to Question as this Issue is informative rather than a bug in our code.

Looks like you've identitifed another very good reason to use version 2.x rather than the JDK Streams (the well known Stream flatMap/filter issue in the JDK is also fixed in version 2.x).

**Comment by johnmcclean** [comment]
Fixed in cyclops 2 and X
