### ISSUE TITLE
Dependency on slf4j-simple

### ISSUE THREAD

**Issue by osebelin** [aol/cyclops-react#525]
The Project adds the following dependencies:
```
compile group: 'org.slf4j', name: 'jcl-over-slf4j', version:'1.7.13'
compile group: 'org.slf4j', name: 'slf4j-simple', version: '1.7.13'
```

Shouldn't it depend on the **slf4j-api** instead of an implementation to make it easier to use in other projects? And why does it depend on jcl-over-slf4j?

**Comment by johnmcclean-aol** [comment]
Thanks for this @osebelin! This definitely looks like an oversight / bug.  

I don't think there is a strong need for a dependency on any logger implementation at all (users should be able to attach exception handlers to log errors themselves).

A quick look at where slf4j is used for logging internally (there are around ~7 locations) I think it can be removed from 6 with no negative impact. We may need to offer an overloaded alternative for Future#quorum that supports logging errors.

**Comment by osebelin** [comment]
I'd like to create a pull request using slf4j-api to support logging errors, but I can't build the project using gradle 3.4.1. Is there a contributors guide?

**Comment by johnmcclean-aol** [comment]
Gradle 2.3 works, I'll add a Gradle Wrapper.

It would be good to upgrade to Gradle 3.x too though.

**Comment by johnmcclean-aol** [comment]
Gradle Wrapper for 2.3 has been added to master.

**Comment by johnmcclean-aol** [comment]
slf4j has been removed as a dependency in https://github.com/aol/cyclops-react/pull/531
