### ISSUE TITLE
Retry within Try.withCatch calls method twice when no errors occur

### ISSUE THREAD

**Issue by jlorenzen** [aol/cyclops-react#552]
When I run the following code I get some unexpected results. This is with version `2.0.0-MI5`.

```java
final String result = Try.withCatch(() -> printAndReturn("first"), RuntimeException.class)
    .retry(__ -> printAndReturn("retry"), 1, 500, TimeUnit.MILLISECONDS)
    .get();
System.out.println("result = " + result);
```

This prints out:
```
first
retry
result = retry
```

Since my private method `printAndReturn` does not throw any exceptions, I would not expect it to invoke the `retry`. Seems like a possible bug?

**Comment by johnmcclean-aol** [comment]
Hey @jlorenzen,

Great question! There are a few of useful methods for this type of situation, that can be used individually or in combination to cover most possible use cases.

* retry
* recover
* recoverWith

# retry

The retry method is equivalent to a map operation that retries. On Try instances map is only ever executed on Success instances. So if the first Try.withCatch fails, retry will not be executed at all. If it succeeds, retry is always executed at least once. 

E.g. In this example we will retry loading from the Db twice if the first call fails.

```java
Try.success("hello")
   .retry(s-> loadFromDb(s),2,500, TimeUnit.MILLISECONDS);
```
E.g. In this example we will never even try loading from the Db
```java
Try.failure("hello")
   .retry(s-> loadFromDb(s),2,500, TimeUnit.MILLISECONDS);
```


# recover

recover executed only on Failure instances, so if the first printAndReturn call succeeds, the second is never executed (alternatively if the first call to printAndReturn fails the second inside recover will be executed).

```java
final String result = Try.withCatch(() -> printAndReturn("first"), RuntimeException.class)
                         .recover(__ -> printAndReturn("retry"))
                         .get();
System.out.println("result = " + result);
```

# recoverWith

recoverWith is a bit like flatMap for recovering, it is executed only on Failure instances but returns a Try instance. This makes it a good candidate to mix recover and retry together to get both recovery from the Failure state and multiple retries on that recovery.

e.g. In the example below if the first call to printAndReturn fails (inside Try.withCatch) then recoverWith will be executed. The recoverWith Function will retry a call to printAndReturn a maximum of twice.

```java
final String result = Try.withCatch(() -> printAndReturn("first"), RuntimeException.class)
    .recoverWith(__ -> Try.<String,RuntimeException>success("ignored")
                          .retry(i->printAndReturn("retry"),2,500, TimeUnit.MILLISECONDS))
                         .get();
System.out.println("result = " + result);
```

### Why retry / recover / recoverWith names

We have two slightly different but related concepts across a number of our core data types. retry is used across most cyclops-react types to indicate a single retryable transformation, that does cause some confusion on types such as Try / Future / Maybe which can enter some form of failure state. On those types recover methods are provided to recover from that state instead.

**Comment by jlorenzen** [comment]
@johnmcclean-aol Interesting. Thanks for the explanation. I've used the `retry` function in the `FluentFunction` classes before and I believe it only runs on failure. So that's probably why I was confused.
But now after studying it some more I see what you mean. Maybe it would be nice to overload the `recover` methods in `Try` with a backoff strategy. Something like:
`recover(__ -> printAndReturn("retry"), 2, 500, MILLISECONDS)`

**Comment by johnmcclean-aol** [comment]
That's a good idea - definetely worth considering as it would result in much cleaner code in for that use case.
