### ISSUE TITLE
public static class µ located in ReactiveSeq interface cause jackson serialisation Exception in AWS EC2

### ISSUE THREAD

**Issue by morrowgi** [aol/cyclops-react#641]
It was noticed when testing on AWS EC2 instances that Jackson Serilizer was constantly throwing the following exception:

com.fasterxml.jackson.databind.JsonMappingException: Type cyclops.stream.ReactiveSeq$µ not present (through reference chain: com.xx.xxx)

When troubleshooting this, it seemed to be related to the following issue open on AWS:
https://forums.aws.amazon.com/thread.jspa?threadID=229364

The only place this can be reproduced is in AWS. The class seems to be filtered out and not present. This issue is to update µ to Mu

**Comment by johnmcclean-aol** [comment]
I think the best approach is to merge the Witness types used for HKT encodings (via the Higher interface) and AnyM - keeps things simpler and also look more natural / java-like.

**Comment by johnmcclean-aol** [comment]
Released in 2.0.0-FINAL
