### ISSUE TITLE
[Code quality] Inconsistence on coding styles. Use of .editorconfig

### ISSUE THREAD

**Issue by quike** [aol/cyclops-react#739]
Current code does not follow any code style/standards defined within the repo so there are some inconsistencies within the project: 

- Mixing space/tab indentation.
- Undefined indentation size.
- Undefined end of line type. 

Same code standard mechanism should be provided so any developer could automatically set his/her environment before contributing to the code base. 

**_Fix Proposal:_**
The use of **.editorconfig** at the root of the project should be solution enough. Compatible with almost all common IDEs, the file indicate the code style used per language inside the current repository and automatically adjust editors to follow the rules included inside.

http://editorconfig.org/

**Comment by johnmcclean** [comment]
Released in M1
