### ISSUE TITLE
Why are the Maven Central artifacts for 10.0.0-FINAL two weeks older than the Git tag?

### ISSUE THREAD

**Issue by seanf** [aol/cyclops-react#911]
Maven Central: https://repo1.maven.org/maven2/com/oath/cyclops/cyclops/10.0.0-FINAL/
vs
Git: https://github.com/aol/cyclops-react/releases/tag/10.0.0-FINAL and https://github.com/aol/cyclops-react/commits/10.0.0-FINAL

BTW Is there a mailing list or something? I don't really like asking silly questions in an issue! This seems like the sort of project that really deserves a mailing list.

**Comment by johnmcclean** [comment]
The tag gets created when the release is created in github, it takes a little bit of effort to fill in the documentation for the release. I'm just back from vacation, and wanted to do the maven release before I went, the release doc for github wasn't complete so I did that when I came back. With hindsight, probably should have held off the release.

Unfortunately there is a minor different between the two - I merged your PR that fixed the javadoc for Either before creating the tag. There are no code changes though.
